added scrapers for 2 more websites
sakethramanujam/crawl-crawl-crawl pull request #2
Opened 2021-05-07 20:33 UTC by pasha009

I copied the format in the main `national_holidays.py`. I don't know if it's better to add options to fetch from a specified website. So for now the code is in separate files with some repeating part.

2021-05-07 20:44 UTC, pasha009 commented
I mistakenly thought that this repo is only for calendar website scrapers 😅. Please ignore previous comment.

2021-05-12 00:12 UTC, sakethramanujam commented
Hello 👋 @pasha009 ! Thanks for your contribution. I suggest that you add them both into a folder with appropriate docs so that it would be easier to use. Let me know incase you need any other inputs. I will test the code tonight and provide comments.
 💯

2021-05-19 22:15 UTC, pasha009 commented
Thanks for showing interest 😄. I am not sure about what stuff to add in the docs. Could you help me by giving some examples of things to put in.

2021-05-20 16:09 UTC, sakethramanujam commented
description about what the scraper does, I mean what website it scrapes and the output data format should be good for starters.

2021-05-20 16:49 UTC, sakethramanujam requested changes

2021-05-20 16:49 UTC, sakethramanujam commented on holidays/README.md
> +scrap websites to generate holiday data in csv format
watch out
[scrape](https://www.merriam-webster.com/dictionary/scrape)
[scrap](https://www.merriam-webster.com/dictionary/scrap)

2021-05-20 16:49 UTC, sakethramanujam commented on holidays/README.md
> +2. `timeanddate.py` scraps https://www.timeanddate.com/holidays/india/
should we have a table like format? like say

|script|website scraped|
|:-|:-|
|something|[abc](something.com)|

2021-05-23 18:01 UTC, pasha009 commented on holidays/README.md
> +2. `timeanddate.py` scraps https://www.timeanddate.com/holidays/india/
Yes, a table makes sense

2021-05-23 18:02 UTC, pasha009 commented on holidays/README.md
> +scrap websites to generate holiday data in csv format
thanks 😅

2021-05-24 18:33 UTC, sakethramanujam approved these changes
LGTM!

2021-05-24 18:34 UTC, merged